In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_raw = pd.read_csv("house_prices_data/train.csv")

df = df_raw.copy()

pd.set_option("display.max_columns", None)

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
print(df.info(), df.columns, sep=f"\n{'-'*100}\n")

print(df.describe())

df.describe(include="object")

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB
None
----------------------------------------------------------------------------------------------------
Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')
                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000
mean    730.500000    56.897260    70.049958   10516.828082     6.099315
std     421.610009    42.300571    24.284752    9981.264932     1.382997
min       1.000000    20.000000    21.000000    1300.000000     1.000000
25%     365.750000    20.000000    59.000000    7553.500000     5.000000
50%     730.500000    50.000000    69.000000    9478.500000     6.000000
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000
max    1460.000000   190.000000   313.000000  215245.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726
std       1.112799    30.202904     20.645407   181.066207   456.098091
min       1.000000  1872.000000   1950.000000     0.000000     0.000000
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000

        BsmtFinSF2    BsmtUnfSF  TotalBsmtSF     1stFlrSF     2ndFlrSF  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000
mean     46.549315   567.240411  1057.429452  1162.626712   346.992466
std     161.319273   441.866955   438.705324   386.587738   436.528436
min       0.000000     0.000000     0.000000   334.000000     0.000000
25%       0.000000   223.000000   795.750000   882.000000     0.000000
50%       0.000000   477.500000   991.500000  1087.000000     0.000000
75%       0.000000   808.000000  1298.250000  1391.250000   728.000000
max    1474.000000  2336.000000  6110.000000  4692.000000  2065.000000

       LowQualFinSF    GrLivArea  BsmtFullBath  BsmtHalfBath     FullBath  \
count   1460.000000  1460.000000   1460.000000   1460.000000  1460.000000
mean       5.844521  1515.463699      0.425342      0.057534     1.565068
std       48.623081   525.480383      0.518911      0.238753     0.550916
min        0.000000   334.000000      0.000000      0.000000     0.000000
25%        0.000000  1129.500000      0.000000      0.000000     1.000000
50%        0.000000  1464.000000      0.000000      0.000000     2.000000
75%        0.000000  1776.750000      1.000000      0.000000     2.000000
max      572.000000  5642.000000      3.000000      2.000000     3.000000

          HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd   Fireplaces  \
count  1460.000000   1460.000000   1460.000000   1460.000000  1460.000000
mean      0.382877      2.866438      1.046575      6.517808     0.613014
std       0.502885      0.815778      0.220338      1.625393     0.644666
min       0.000000      0.000000      0.000000      2.000000     0.000000
25%       0.000000      2.000000      1.000000      5.000000     0.000000
50%       0.000000      3.000000      1.000000      6.000000     1.000000
75%       1.000000      3.000000      1.000000      7.000000     1.000000
max       2.000000      8.000000      3.000000     14.000000     3.000000

       GarageYrBlt   GarageCars   GarageArea   WoodDeckSF  OpenPorchSF  \
count  1379.000000  1460.000000  1460.000000  1460.000000  1460.000000
mean   1978.506164     1.767123   472.980137    94.244521    46.660274
std      24.689725     0.747315   213.804841   125.338794    66.256028
min    1900.000000     0.000000     0.000000     0.000000     0.000000
25%    1961.000000     1.000000   334.500000     0.000000     0.000000
50%    1980.000000     2.000000   480.000000     0.000000    25.000000
75%    2002.000000     2.000000   576.000000   168.000000    68.000000
max    2010.000000     4.000000  1418.000000   857.000000   547.000000

       EnclosedPorch    3SsnPorch  ScreenPorch     PoolArea       MiscVal  \
count    1460.000000  1460.000000  1460.000000  1460.000000   1460.000000
mean       21.954110     3.409589    15.060959     2.758904     43.489041
std        61.119149    29.317331    55.757415    40.177307    496.123024
min         0.000000     0.000000     0.000000     0.000000      0.000000
25%         0.000000     0.000000     0.000000     0.000000      0.000000
50%         0.000000     0.000000     0.000000     0.000000      0.000000
75%         0.000000     0.000000     0.000000     0.000000      0.000000
max       552.000000   508.000000   480.000000   738.000000  15500.000000

            MoSold       YrSold      SalePrice
count  1460.000000  1460.000000    1460.000000
mean      6.321918  2007.815753  180921.195890
std       2.703626     1.328095   79442.502883
min       1.000000  2006.000000   34900.000000
25%       5.000000  2007.000000  129975.000000
50%       6.000000  2008.000000  163000.000000
75%       8.000000  2009.000000  214000.000000
max      12.000000  2010.000000  755000.000000

/tmp/ipykernel_5817/3881032934.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,588,1460,1460,1460,1423,1423,1422,1423,1422,1460,1460,1460,1459,1460,1460,770,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,8,5,8,6,8,15,16,3,4,5,6,4,4,4,6,6,6,5,2,5,4,7,5,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,TA,TA,PConc,TA,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Gd,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,1445,1220,726,1141,1434,515,504,445,906,1282,647,649,1311,953,430,1256,1428,741,1365,1334,735,1360,380,870,605,1311,1326,1340,3,157,49,1267,1198

In [6]:
num_cols = df.select_dtypes(include="number")

num_cols.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64
 10  BsmtFinSF2     1460 non-null   int64
 11  BsmtUnfSF      1460 non-null   int64
 12  TotalBsmtSF    1460 non-null   int64
 13  1stFlrSF       1460 non-null   int64
 14  2ndFlrSF       1460 non-null   int64
 15  LowQualFinSF   1460 non-null   int64
 16  GrLivArea      1460 non-null   int64
 17  BsmtFullBath   1460 non-null   int64
 18  BsmtHalfBath   1460 non-null   int64
 19  FullBath       1460 non-null   int64
 20  HalfBath       1460 non-null   int64
 21  BedroomAbvGr   1460 non-null   int64
 22  KitchenAbvGr   1460 non-null   int64
 23  TotRmsAbvGrd   1460 non-null   int64
 24  Fireplaces     1460 non-null   int64
 25  GarageYrBlt    1379 non-null   float64
 26  GarageCars     1460 non-null   int64
 27  GarageArea     1460 non-null   int64
 28  WoodDeckSF     1460 non-null   int64
 29  OpenPorchSF    1460 non-null   int64
 30  EnclosedPorch  1460 non-null   int64
 31  3SsnPorch      1460 non-null   int64
 32  ScreenPorch    1460 non-null   int64
 33  PoolArea       1460 non-null   int64
 34  MiscVal        1460 non-null   int64
 35  MoSold         1460 non-null   int64
 36  YrSold         1460 non-null   int64
 37  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35)
memory usage: 433.6 KB

In [7]:
obj_cols = df.select_dtypes(include="object")

obj_cols.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 43 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       1460 non-null   str
 1   Street         1460 non-null   str
 2   Alley          91 non-null     str
 3   LotShape       1460 non-null   str
 4   LandContour    1460 non-null   str
 5   Utilities      1460 non-null   str
 6   LotConfig      1460 non-null   str
 7   LandSlope      1460 non-null   str
 8   Neighborhood   1460 non-null   str
 9   Condition1     1460 non-null   str
 10  Condition2     1460 non-null   str
 11  BldgType       1460 non-null   str
 12  HouseStyle     1460 non-null   str
 13  RoofStyle      1460 non-null   str
 14  RoofMatl       1460 non-null   str
 15  Exterior1st    1460 non-null   str
 16  Exterior2nd    1460 non-null   str
 17  MasVnrType     588 non-null    str
 18  ExterQual      1460 non-null   str
 19  ExterCond      1460 non-null   str
 20  Foundation     1460 non-null   str
 21  BsmtQual       1423 non-null   str
 22  BsmtCond       1423 non-null   str
 23  BsmtExposure   1422 non-null   str
 24  BsmtFinType1   1423 non-null   str
 25  BsmtFinType2   1422 non-null   str
 26  Heating        1460 non-null   str
 27  HeatingQC      1460 non-null   str
 28  CentralAir     1460 non-null   str
 29  Electrical     1459 non-null   str
 30  KitchenQual    1460 non-null   str
 31  Functional     1460 non-null   str
 32  FireplaceQu    770 non-null    str
 33  GarageType     1379 non-null   str
 34  GarageFinish   1379 non-null   str
 35  GarageQual     1379 non-null   str
 36  GarageCond     1379 non-null   str
 37  PavedDrive     1460 non-null   str
 38  PoolQC         7 non-null      str
 39  Fence          281 non-null    str
 40  MiscFeature    54 non-null     str
 41  SaleType       1460 non-null   str
 42  SaleCondition  1460 non-null   str
dtypes: str(43)
memory usage: 490.6 KB

/tmp/ipykernel_5817/2743083165.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df.select_dtypes(include="object")

Разбил dataframe на числовые и нечисловые колонки, чтобы отдельно изучить каждые признаки

In [8]:
missing = df.isnull().sum().sort_values(ascending=False)

missing[missing>0]

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageQual        81
GarageFinish      81
GarageType        81
GarageYrBlt       81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtQual          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

In [9]:
for col in missing.index[:7]:
    print(col)
    print(df[col].value_counts(dropna=False))
    print()

PoolQC
PoolQC
NaN    1453
Gd        3
Ex        2
Fa        2
Name: count, dtype: int64

MiscFeature
MiscFeature
NaN     1406
Shed      49
Gar2       2
Othr       2
TenC       1
Name: count, dtype: int64

Alley
Alley
NaN     1369
Grvl      50
Pave      41
Name: count, dtype: int64

Fence
Fence
NaN      1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

MasVnrType
MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

FireplaceQu
FireplaceQu
NaN    690
Gd     380
TA     313
Fa      33
Ex      24
Po      20
Name: count, dtype: int64

LotFrontage
LotFrontage
NaN      259
60.0     143
70.0      70
80.0      69
50.0      57
        ...
138.0      1
160.0      1
152.0      1
153.0      1
46.0       1
Name: count, Length: 111, dtype: int64

Оценил пропуски в колонках PoolQC, MiscFeature и Alley буду удалять из-за слишком большого количество null и малоинформативности, остальные буду корректировать

In [10]:
df.loc[~df["MasVnrType"].notnull(), "MasVnrArea"].value_counts(dropna=False)

MasVnrArea
0.0      859
NaN        8
1.0        2
288.0      1
344.0      1
312.0      1
Name: count, dtype: int64

Нашел аномалию для MasVnrArea, если type null то area может быть >0, следовалетьно тип скорее всего missing и надо это учесть в type а все остальное сделать none

In [11]:
df.drop(missing.index[:3], axis=1, inplace=True)

In [12]:
df.loc[~df["Fence"].notnull(), "Fence"] = "None"

df.loc[~df["FireplaceQu"].notnull(), "FireplaceQu"] = "None"

(~df.notnull()).sum().sort_values(ascending=False)

MasVnrType       872
LotFrontage      259
GarageCond        81
GarageFinish      81
GarageType        81
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 78, dtype: int64

Удалил три первые по пропускам колонки PoolQC, MiscFeature, Alley и заменил null на None в Fence и FireplaceQu

In [13]:
df.loc[~df["MasVnrType"].notnull() & df["MasVnrArea"]>0, "MasVnrType"] = "Missing"

df.loc[~df["MasVnrType"].notnull(), "MasVnrType"] = "None"

df.loc[~df["MasVnrArea"].notnull(), "MasVnrArea"] = 0

missing = (~df.notnull()).sum().sort_values(ascending=False)

missing[missing>0]

LotFrontage     259
GarageYrBlt      81
GarageCond       81
GarageFinish     81
GarageType       81
GarageQual       81
BsmtFinType2     38
BsmtExposure     38
BsmtQual         37
BsmtCond         37
BsmtFinType1     37
Electrical        1
dtype: int64

In [14]:
df[missing.index].value_counts(dropna=False)

LotFrontage  GarageYrBlt  GarageCond  GarageFinish  GarageType  GarageQual  BsmtFinType2  BsmtExposure  BsmtQual  BsmtCond  BsmtFinType1  Electrical  MSSubClass  Id    Condition2  Condition1  Neighborhood  LandSlope  LotConfig  Utilities  LandContour  LotShape  Street  LotArea  MSZoning  MasVnrType  RoofMatl  Exterior1st  OverallQual  BldgType  Foundation  ExterCond  ExterQual  MasVnrArea  Exterior2nd  BsmtFinSF1  BsmtUnfSF  BsmtFinSF2  TotalBsmtSF  Heating  HeatingQC  HouseStyle  YearBuilt  YearRemodAdd  RoofStyle  OverallCond  GrLivArea  LowQualFinSF  2ndFlrSF  1stFlrSF  CentralAir  BsmtHalfBath  BedroomAbvGr  BsmtFullBath  TotRmsAbvGrd  KitchenQual  KitchenAbvGr  Functional  FireplaceQu  Fireplaces  FullBath  HalfBath  GarageArea  GarageCars  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  Fence  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice
65.0         2003.0       TA          RFn           Attchd      TA          Unf           No            Gd        TA        GLQ           SBrkr       60          1     Norm        Norm        CollgCr       Gtl        Inside     AllPub     Lvl          Reg       Pave    8450     RL        BrkFace     CompShg   VinylSd      7            1Fam      PConc       TA         Gd         196.0       VinylSd      706         150        0           856          GasA     Ex         2Story      2003       2003          Gable      5            1710       0             854       856       Y           0             3             1             8             Gd           1             Typ         None         0           2         1         548         2           Y           0           61           0              0          0            0         None   0        2       2008    WD        Normal         208500       1
80.0         1976.0       TA          RFn           Attchd      TA          Unf           Gd            Gd        TA        ALQ           SBrkr       20          2     Norm        Feedr       Veenker       Gtl        FR2        AllPub     Lvl          Reg       Pave    9600     RL        None        CompShg   MetalSd      6            1Fam      CBlock      TA         TA         0.0         MetalSd      978         284        0           1262         GasA     Ex         1Story      1976       1976          Gable      8            1262       0             0         1262      Y           1             3             0             6             TA           1             Typ         TA           1           2         0         460         2           Y           298         0            0              0          0            0         None   0        5       2007    WD        Normal         181500       1
68.0         2001.0       TA          RFn           Attchd      TA          Unf           Mn            Gd        TA        GLQ           SBrkr       60          3     Norm        Norm        CollgCr       Gtl        Inside     AllPub     Lvl          IR1       Pave    11250    RL        BrkFace     CompShg   VinylSd      7            1Fam      PConc       TA         Gd         162.0       VinylSd      486         434        0           920          GasA     Ex         2Story      2001       2002          Gable      5            1786       0             866       920       Y           0             3             1             6             Gd           1             Typ         TA           1           2         1         608         2           Y           0           42           0              0          0            0         None   0        9       2008    WD        Normal         223500       1
60.0         1998.0       TA          Unf           Detchd      TA          Unf           No            TA        Gd        ALQ           SBrkr       70          4     Norm        Norm        Crawfor       Gtl        Corner     AllPub     Lvl          IR1       Pave    9550     RL        None        CompShg   Wd Sdng      7            1Fam      BrkTil      TA         TA         0.0         Wd Shng      216         540        0           756          GasA     Gd         2Story      1915       1970          Gable      5            1717       0             756       961       Y           0             3             1             7             Gd           1             Typ         Gd           1           1         0         642         3           Y           0           35           272            0          0            0         None   0        2       2006    WD        Abnorml        140000       1
84.0         2000.0       TA          RFn           Attchd      TA          Unf           Av            Gd        TA        GLQ           SBrkr       60          5     Norm        Norm        NoRidge       Gtl        FR2        AllPub     Lvl          IR1       Pave    14260    RL        BrkFace     CompShg   VinylSd      8            1Fam      PConc       TA         Gd         350.0       VinylSd      655         490        0           1145         GasA     Ex         2Story      2000       2000          Gable      5            2198       0             1053      1145      Y           0             4             1             9             Gd           1             Typ         TA           1           2         1         836         3           Y           192         84           0              0          0            0         None   0        12      2008    WD        Normal         250000       1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
62.0         1999.0       TA          RFn           Attchd      TA          Unf           No            Gd        TA        Unf           SBrkr       60          1456  Norm        Norm        Gilbert       Gtl        Inside     AllPub     Lvl          Reg       Pave    7917     RL        None        CompShg   VinylSd      6            1Fam      PConc       TA         TA         0.0         VinylSd      0           953        0           953          GasA     Ex         2Story      1999       2000          Gable      5            1647       0             694       953       Y           0             3             0             7             TA           1             Typ         TA           1           2         1         460         2           Y           0           40           0              0          0            0         None   0        8       2007    WD        Normal         175000       1
85.0         1978.0       TA          Unf           Attchd      TA          Rec           No            Gd        TA        ALQ           SBrkr       20          1457  Norm        Norm        NWAmes        Gtl        Inside     AllPub     Lvl          Reg       Pave    13175    RL        Stone       CompShg   Plywood      6            1Fam      CBlock      TA         TA         119.0       Plywood      790         589        163         1542         GasA     TA         1Story      1978       1988          Gable      6            2073       0             0         2073      Y           0             3             1             7             TA           1             Min1        TA           2           2         0         500         2           Y           349         0            0              0          0            0         MnPrv  0        2       2010    WD        Normal         210000       1
66.0         1941.0       TA          RFn           Attchd      TA          Unf           No            TA        Gd        GLQ           SBrkr       70          1458  Norm        Norm        Crawfor       Gtl        Inside     AllPub     Lvl          Reg       Pave    9042     RL        None        CompShg   CemntBd      7            1Fam      Stone       Gd         Ex         0.0         CmentBd      275         877        0           1152         GasA     Ex         2Story      1941       2006          Gable      9            2340       0             1152      1188      Y           0             4             0             9             Gd           1             Typ         Gd           2           2         0         252         1           Y           0           60           0              0          0            0         GdPrv  2500     5       2010    WD        Normal         266500       1
68.0         1950.0       TA          Unf           Attchd      TA          Rec           Mn            TA        TA        GLQ           FuseA       20          1459  Norm        Norm        NAmes         Gtl        Inside     AllPub     Lvl          Reg       Pave    9717     RL        None        CompShg   MetalSd      5            1Fam      CBlock      TA         TA         0.0         MetalSd      49          0          1029        1078         GasA     Gd         1Story      1950       1996          Hip        6            1078       0             0         1078      Y           0             2             1             5             Gd           1             Typ         None         0           1         0         240         1           Y           366         0            112            0          0            0         None   0        4       2010    WD        Normal         142125       1
75.0         1965.0       TA          Fin           Attchd      TA          LwQ           No            TA        TA        BLQ           SBrkr       20          1460  Norm        Norm        Edwards       Gtl        Inside     AllPub     Lvl          Reg       Pave    9937     RL        None        CompShg   HdBoard      5            1Fam      CBlock      TA         Gd         0.0         HdBoard      830         136        290         1256         GasA     Gd         1Story      1965       1965          Gable      6            1256       0             0         1256      Y           0             3             1             6             TA           1             Typ         None         0           1         1         276         1           Y           736         68           0              0          0            0         None   0        6       2008    WD        Normal         147500       1
Name: count, Length: 1460, dtype: int64